--changeset guzev.dev@gmail.com:1
CREATE TABLE CURRENCY_LOG (
    ID                      SERIAL PRIMARY KEY,
    BASE_CURRENCY_CODE      VARCHAR(3) NOT NULL,
    ANOTHER_CURRENCY_CODE   VARCHAR(3) NOT NULL,
    RATE                    DECIMAL NOT NULL,
    RATE_DATE_TIME          TIMESTAMP NULL,
    DOUBLE_CONVERSION       BOOLEAN DEFAULT FALSE,
    CREATION_DATE           TIMESTAMP NULL,

    FOREIGN KEY (BASE_CURRENCY_CODE) REFERENCES CURRENCY(CURRENCY_CODE),
    FOREIGN KEY (ANOTHER_CURRENCY_CODE) REFERENCES CURRENCY(CURRENCY_CODE)
);
--rollback DROP TABLE CURRENCY_LOG;