spring:
  application:
    name: tz
  config:
    import: file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange_rates
    username: ${EXCHANGE_RATES_DB_USER}
    password: ${EXCHANGE_RATES_DB_PASSWORD}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

integration:
  exchangeRates:
    host: http://data.fixer.io/api
    apiKey: ${INTEGRATION_EXCHANGE_RATE_API_KEY}
    baseCurrency: EUR

currencyRate:
  fetch:
    frequency: 3600
